### ISSUE TITLE
Item duping glitch related to Cries

### ISSUE THREAD

**Issue by mauvesea** [dannye/pokered-crysaudio#8]
There's an issue related to the DisplayPokedex/PlayCry function.

By checking Vaporeon's or Jolteon's dex entry in Bill's House, the 6th item slot is multiplied, just like the regular MissingNo. glitch.

It's related to the species cry/index number. Skipping the PlayCry routine or skipping the IndexToPokedex routine does not reproduces the issue. I was unable to figure out why the glitch was happening.

**Comment by dannye** [comment]
Fixed via 9a848bd603eb8603e4459537e3dab96390270004.
